use [sequence]

select * from UACT9fb7f569f014441cb9d8b966ee165672

--where worksitedocumentid = 339767000 -- Enter the WorkSite Document ID that appears when running the Workflow Instance ID

where WorkItemInstanceId = 9826437 --Enter here the Workflow Instance ID for the whole process


--use [sequence]

--select * from UACT9fb7f569f014441cb9d8b966ee165672

----where worksitedocumentid = 339767000 -- Enter the WorkSite Document ID that appears when running the Workflow Instance ID

--where WorkItemInstanceId = 7447306 --Enter here the Workflow Instance ID for the whole process
